Repository theislab/cellrank, pull requests merged in 2021-09, with the labels that each got.

#696 Add WOT thresholding
  cellrank/external/kernels/_wot_kernel.py
  tests/test_external.py
Labels: feature

#735 Update `notes-dev.rst`
  docs/source/release/changelog/696.feature.rst
  docs/source/release/notes-dev.rst
  tox.ini
Labels: ignore-towncrier

#737 Fix WOT unused kwargs
  cellrank/external/kernels/_wot_kernel.py
  tests/test_external.py
Labels: bugfix

#740 Fix workflow files
  .github/workflows/deployment.yml
  .github/workflows/news.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.rst
  cellrank/datasets/_datasets.py
  cellrank/tl/estimators/_base_estimator.py
  docs/Makefile
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/release/notes-1.3.0.rst
  tox.ini
Labels: bugfix

#742 Fix cluster_lineage ax
  cellrank/pl/_cluster_lineage.py
Labels: bugfix

#743 Fix/docstrings
  .github/workflows/news.yml
  .github/workflows/release.yml
  cellrank/pl/_heatmap.py
  cellrank/pl/_log_odds.py
  cellrank/pl/_utils.py
  cellrank/tl/_colors.py
  cellrank/tl/_init_term_states.py
  cellrank/tl/_lineage.py
  cellrank/tl/_lineages.py
  cellrank/tl/_linear_solver.py
  cellrank/tl/_transition_matrix.py
  cellrank/tl/_utils.py
  cellrank/tl/estimators/mixins/_lineage_drivers.py
  cellrank/tl/estimators/terminal_states/_cflare.py
  cellrank/tl/estimators/terminal_states/_gpcca.py
  cellrank/tl/estimators/terminal_states/_term_states_estimator.py
  cellrank/tl/kernels/_base_kernel.py
  cellrank/tl/kernels/_connectivity_kernel.py
  cellrank/tl/kernels/_pseudotime_kernel.py
  cellrank/tl/kernels/_tmat_flow.py
  cellrank/tl/kernels/_utils.py
  cellrank/tl/kernels/_velocity_kernel.py
  cellrank/tl/kernels/_velocity_schemes.py
  cellrank/ul/_docs.py
  cellrank/ul/_utils.py
  cellrank/ul/models/_base_model.py
  cellrank/ul/models/_gamr_model.py
  cellrank/ul/models/_pygam_model.py
  cellrank/ul/models/_sklearn_model.py
  cellrank/ul/models/_utils.py
  docs/requirements.txt
  docs/source/_ext/typed_returns.py
  docs/source/classes.rst
  docs/source/conf.py
  docs/source/release/changelog/695.deprecation.rst
  docs/source/release/changelog/696.feature.rst
  docs/source/release/changelog/701.bugfix.rst
  docs/source/release/changelog/705.misc.rst
  docs/source/release/changelog/709.bugfix.rst
  docs/source/release/changelog/712.doc.rst
  docs/source/release/changelog/726.feature.rst
  docs/source/release/changelog/727.feature.rst
  docs/source/release/changelog/737.bugfix.rst
  docs/source/release/changelog/738.bugfix.rst
  docs/source/release/changelog/742.bugfix.rst
  docs/source/release/notes-dev.rst
Labels: doc
