Repository theislab/cellrank, pull requests merged in 2022-06, with the labels that each got.

#879 Feature/eigen updates
  cellrank/estimators/mixins/decomposition/_eigen.py
  tests/_ground_truth_figures/gpcca_coarse_T_stat_init_dist.png
  tests/_ground_truth_figures/gpcca_complex_spectrum.png
  tests/_ground_truth_figures/gpcca_real_spectrum.png
  tests/_ground_truth_figures/gpcca_real_spectrum_hide_eigengap.png
  tests/_ground_truth_figures/gpcca_spectrum_evals.png
  tests/_ground_truth_figures/gpcca_spectrum_evals_complex.png
  tests/_ground_truth_figures/gpcca_spectrum_title.png
  tests/_ground_truth_figures/mc_complex_spectrum.png
  tests/_ground_truth_figures/mc_kwargs_linewidths.png
  tests/_ground_truth_figures/mc_marker.png
  tests/_ground_truth_figures/mc_real_spectrum.png
  tests/_ground_truth_figures/mc_real_spectrum_hide_eigengap.png
  tests/_ground_truth_figures/mc_real_spectrum_hide_xticks.png
  tests/_ground_truth_figures/mc_spectrum.png
  tests/_ground_truth_figures/mc_spectrum_evals.png
  tests/_ground_truth_figures/mc_spectrum_evals_complex.png
  tests/_ground_truth_figures/mc_spectrum_title.png
Labels: feature

#880 Feature/scverse zulip
  README.rst
  docs/source/index.rst
  tox.ini
Labels: doc

#883 Feature/update references
  docs/source/references.bib
Labels: doc

#886 Feature/bone marrow data
  cellrank/datasets/__init__.py
  cellrank/datasets/_datasets.py
  docs/source/api.rst
Labels: feature

#890 Add argument `subset_to_serum`
  cellrank/datasets/_datasets.py
Labels: feature

#901 Fix/rtd submodules
  .readthedocs.yml
  .rstcheck.cfg
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/tutorials.rst
Labels: doc

#915 Fix/precomputed kernel adata
  cellrank/kernels/_precomputed_kernel.py
  tests/test_kernels.py
Labels: bugfix

#914 Prefer plotting of discrete values
  cellrank/estimators/mixins/_utils.py
Labels: misc

#916 Allow reading kernels from AnnData
  cellrank/kernels/_base_kernel.py
  cellrank/kernels/_precomputed_kernel.py
  cellrank/kernels/mixins/_kernel.py
  tests/test_kernels.py
Labels: feature

#913 Compute 20 Schur vectors by default
  cellrank/estimators/mixins/decomposition/_schur.py
  cellrank/estimators/terminal_states/_gpcca.py
  tests/_ground_truth_figures/gpcca_complex_spectrum.png
Labels: misc
