Repository theislab/cellrank, pull requests merged in 2023-05, with the labels that each got.

#1025 allow data and velocity to be read from obsm (as needed for MongeVelo…
  cellrank/kernels/_velocity_kernel.py
  tests/test_kernels.py
Labels: enhancement

#1034 Fix `adjustText` modifying data in-place
  cellrank/estimators/mixins/_lineage_drivers.py
Labels: bugfix

#1037 Pass `kwargs` in `set_{initial,terminal}_states`
  cellrank/estimators/terminal_states/_gpcca.py
Labels: bug

#1043 Fix gene trends colors
  cellrank/pl/_gene_trend.py
Labels: bugfix
